# Лекция 3 - ДЗ в конце

In [44]:
import numpy as np
import pandas as pd

In [45]:
# Series, DataFrame, Index - структуры Pandas

data = pd.Series([0.25, 0.5, 0.75, 1.0])
print(data)
print(type(data))
print(type(data.values))
print(data.index)
print(type(data.index))

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64
<class 'pandas.core.series.Series'>
<class 'numpy.ndarray'>
RangeIndex(start=0, stop=4, step=1)
<class 'pandas.core.indexes.range.RangeIndex'>

In [46]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
print (data[0])
print (data[1:3])
# индексы определяем явно, как хотим
data = pd.Series([0.25, 0.5, 0.75, 1.0], index = ['a', 'b', 'c', 'd'])
print (data)
print (data['a'])
print (data['b':'d'])

print(type(data.index))

0.25
1    0.50
2    0.75
dtype: float64
a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64
0.25
b    0.50
c    0.75
d    1.00
dtype: float64
<class 'pandas.core.indexes.base.Index'>

In [47]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index = [1, 10, 7, 'd'])
print (data)

print (data[1])
print (data[10:'d'])

1     0.25
10    0.50
7     0.75
d     1.00
dtype: float64
0.25
10    0.50
7     0.75
d     1.00
dtype: float64

In [48]:
population_dict = {
    'city_1': 1001,
    'city_2': 1002,
    'city_3': 1003,
    'city_4': 1004,
    'city_5': 1005,
}
population = pd.Series(population_dict)
print (population)

print (population['city_4'])
print (population['city_4':'city_5'])

city_1    1001
city_2    1002
city_3    1003
city_4    1004
city_5    1005
dtype: int64
1004
city_4    1004
city_5    1005
dtype: int64

In [49]:
# DataFrame - несколько сирис вместе
population_dict = {
    'city_1': 1001,
    'city_2': 1002,
    'city_3': 1003,
    'city_4': 1004,
    'city_5': 1005,
}
area_dict = {
    'city_1': 1,
    'city_2': 2,
    'city_3': 3,
    'city_4': 4,
    'city_5': 5,
}
population = pd.Series(population_dict)
area = pd.Series(area_dict)

print (area)

states = pd.DataFrame({
    'population1': population,
    'area1': area,
})
print (states)

print (states.values)
print (states.index)
print (states.columns)

print (type(states.values))
print (type(states.index))
print (type(states.columns))

print (states['area1'])

city_1    1
city_2    2
city_3    3
city_4    4
city_5    5
dtype: int64
        population1  area1
city_1         1001      1
city_2         1002      2
city_3         1003      3
city_4         1004      4
city_5         1005      5
[[1001    1]
 [1002    2]
 [1003    3]
 [1004    4]
 [1005    5]]
Index(['city_1', 'city_2', 'city_3', 'city_4', 'city_5'], dtype='object')
Index(['population1', 'area1'], dtype='object')
<class 'numpy.ndarray'>
<class 'pandas.core.indexes.base.Index'>
<class 'pandas.core.indexes.base.Index'>
city_1    1
city_2    2
city_3    3
city_4    4
city_5    5
Name: area1, dtype: int64

In [50]:
# Index
ind = pd.Index([2,3,5,7,11])
print (ind[1])
print (ind[::2])

indA = pd.Index([1,2,3,4,5])
indB = pd.Index([2,3,4,5,6])

print (indA.intersection(indB))

3
Index([2, 5, 11], dtype='int64')
Index([2, 3, 4, 5], dtype='int64')

In [51]:
# Выборка данных
data = pd.Series([0.25, 0.5, 0.75, 1.0], index = ['a', 'b', 'c', 'd'])
print ('a' in data)
print ('z' in data)

print (data.keys())
print (list(data.items()))

data['a'] = 100
data['z'] = 1000

print (data)

# одномер массив
data = pd.Series([0.25, 0.5, 0.75, 1.0], index = ['a', 'b', 'c', 'd'])

print (data['a':'c'])
print (data[0:2])
print (data[(data > 0.5) & (data < 1)])
print (data[['a', 'd']])

True
False
Index(['a', 'b', 'c', 'd'], dtype='object')
[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]
a     100.00
b       0.50
c       0.75
d       1.00
z    1000.00
dtype: float64
a    0.25
b    0.50
c    0.75
dtype: float64
a    0.25
b    0.50
dtype: float64
c    0.75
dtype: float64
a    0.25
d    1.00
dtype: float64

In [52]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=[1, 3, 10, 15])

print(data[1]) 
print(data.loc[1])
print(data.iloc[1])

0.25
0.25
0.5

In [53]:
data = pd.DataFrame({"area": area, "population": population, "pop": population})
print (data)

print(data["area"])
print(data.area)
print(data.population is data["population"])
print(data.population is data["pop"])

        area  population   pop
city_1     1        1001  1001
city_2     2        1002  1002
city_3     3        1003  1003
city_4     4        1004  1004
city_5     5        1005  1005
city_1    1
city_2    2
city_3    3
city_4    4
city_5    5
Name: area, dtype: int64
city_1    1
city_2    2
city_3    3
city_4    4
city_5    5
Name: area, dtype: int64
True
False

In [54]:
data["new"] = data["area"]
data["new1"] = data["area"] / data["pop"]
print(data)

        area  population   pop  new      new1
city_1     1        1001  1001    1  0.000999
city_2     2        1002  1002    2  0.001996
city_3     3        1003  1003    3  0.002991
city_4     4        1004  1004    4  0.003984
city_5     5        1005  1005    5  0.004975

In [ ]:
data = pd.DataFrame({"area": area, "population": population, "pop": population})
print(data.values)
print(data.T)
print(data.values[0])

In [ ]:
print(data.iloc[:3, 1:2])
print(data.loc[:"city_4", "population":"pop"])
print(data.loc[data["pop"] > 1002, ["area", "pop"]])

In [ ]:
data.iloc[0, 2] = 99999
print (data)

In [ ]:
rng = np.random.default_rng()
s = pd.Series(rng.integers(0, 10, 4))

print(s)
print(np.exp(s))

In [ ]:
dfA = pd.DataFrame(rng.integers(0, 10, (2, 2)), columns=['a', 'b'])
dfB = pd.DataFrame(rng.integers(0, 10, (3, 3)), columns=['a', 'b', 'c'])

print(dfA)
print(dfB)
print(dfA + dfB)

In [ ]:
rng = np.random.default_rng(1)
A = rng.integers(0, 10, (3, 4))
print(A)
print(A[0])
print(A - A[0])

In [ ]:
df = pd.DataFrame(A, columns=['a', 'b', 'c', 'd'])
print(df)
print(df.iloc[0])
print(df - df.iloc[0])
print(df - df.iloc[0, ::2])

In [ ]:
NA - values: NULL, NaN, -99999

In [ ]:
val1 = np.array([1, 2, 3])
print(val1.sum())

In [ ]:
val1 = np.array([1, np.nan, 2, 3])

print(val1)
print(val1.sum())
print(np.nansum(val1))

In [ ]:
x = pd.Series(range(10), dtype=int)
print(x)

In [ ]:
x[0] = None
x[1] = np.nan

print(x)

In [ ]:
x1 = pd.Series(['a', 'b', 'c'])
x1[0] = None
x1[1] = np.nan

print(x1)

In [ ]:
x2 = pd.Series([1, 2, 3, np.nan, None, pd.NA])
print(x2)

In [ ]:
x3 = pd.Series([1, 2, 3, np.nan, None, pd.NA], dtype='Int32')
print(x3)

print(x3.isnull())
print(x3[x3.isnull()])
print(x3[x3.notnull()])
print(x3.dropna())

In [ ]:
df = pd.DataFrame(
    [
        [1, 2, 3, np.nan, None, pd.NA],
        [1, 2, 3, None, 5, 6],
        [1, np.nan, 3, None, np.nan, 6]
    ]
)
print(df)
print(df.dropna())
print(df.dropna(axis=0))
print(df.dropna(axis=1))

In [ ]:
# any , all, thresh
print(df.dropna(axis=1, how="all"))
print(df.dropna(axis=1, how="any"))
print(df.dropna(axis=1, thresh=2))

# Домашнее задание, №1

In [ ]:
data = pd.Series([1, 2, 3, 4, 5])
print(data)

In [68]:
data = pd.Series(
    {
        'a': 1,
        'b': 2,
        'c': 3,
        'd': 4,
        'e': 5
    }
)
print(data)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [70]:
data = pd.Series(10, index=['a', 'b', 'c', 'd', 'e'])
print(data)

a    10
b    10
c    10
d    10
e    10
dtype: int64

# №2

In [76]:
data1 = pd.Series([1, 2, 3, 4, 5])
data2 = pd.Series([6, 7, 8, 9, 10])

df = pd.DataFrame([data1, data2])
print(df)

   0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10

In [78]:
data = [
    {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5},
    {'a': 6, 'b': 7, 'c': 8, 'd': 9, 'e': 10}
]

df = pd.DataFrame(data)
print(df)

   a  b  c  d   e
0  1  2  3  4   5
1  6  7  8  9  10

In [80]:
df = pd.DataFrame({"col1": data1, "col2": data2})
print(df)

   data1  data2
0      1      6
1      2      7
2      3      8
3      4      9
4      5     10

In [86]:
arr = np.random.random((3, 3))
df = pd.DataFrame(arr)

print(df)

          0         1         2
0  0.166727  0.950570  0.961383
1  0.886340  0.949703  0.890179
2  0.350374  0.645498  0.605416

In [88]:
data = np.array([(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd'), (5, 'e')], dtype=[('num', 'int64'), ('char', 'U10')])
df = pd.DataFrame(data)

print(df)

   num char
0    1    a
1    2    b
2    3    c
3    4    d
4    5    e

# №3

In [ ]:
population_dict = {
    "city_1": 1,
    "city_2": 2,
    "city_3": 3,
    "city_41": 4,
    "city_51": 5,
}

area_dict = {
    "city_1": 10,
    "city_2": 11,
    "city_3": 12,
    "city_42": 13,
    "city_52": 14,
}

population = pd.Series(population_dict)
area = pd.Series(area_dict)

states = pd.DataFrame({
    "population": population,
    "area": area,
})

states.fillna(1)

# №4

In [100]:
rng = np.random.default_rng(5)
A = rng.integers(0, 100, (5, 4))
print(A)

[[67 80  2 80]
 [46 51 63 28]
 [97  5 27 38]
 [57 40 13  4]
 [ 0  4 14 99]]

In [94]:
df = pd.DataFrame(A, columns=['a', 'b', 'c', 'd'])
df

   a  b  c  d
0  4  5  7  9
1  0  1  8  9
2  2  3  8  4

In [102]:
print(df.iloc[:, 0])
print(df.sub(df.iloc[:, 0], axis=0))

0    4
1    0
2    2
Name: a, dtype: int64
   a  b  c  d
0  0  1  3  5
1  0  1  8  9
2  0  1  6  2

# №5

In [107]:
data = {'a': [1, np.nan, np.nan, 4], 'b': [np.nan, 2, 3, np.nan]}
df = pd.DataFrame(data)
df

df.ffill()
df.bfill()

     a    b
0  1.0  2.0
1  4.0  2.0
2  4.0  3.0
3  4.0  NaN